### ISSUE TITLE
Unknown explicit YAML type tags

### ISSUE THREAD

**Issue by kavon** [kavon/yaml-ast#1]
YAML allows for explicit type specifiers for values in the file: http://yaml.org/spec/1.1/#id858600

Thus, while the YAML output below is correct according to the spec, we cannot handle the type specifiers here because it has never heard of these Python classes, and so a parsing error occurs.

I think the best way to fix this is to look for and scrub all explicit type tags so that the tool can still work on the well-formed YAML below: 

```
!Program
externs: []
funcs:
- !Function
  block:
  - !PrintStmt
    keyword: print
    stmt: '513'
  - !PrintStmt
    keyword: print
    stmt: hello, world!
  - !PrintStmt
    keyword: print
    stmt: '   '
  - !PrintStmt
    keyword: print
    stmt: 333
  decls: []
  id: run
  type: void
```
